# Generated by Django 4.2.2 on 2023-06-19 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('data_Pub', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolvido', models.BooleanField()),
                ('dataEmprestimo', models.DateTimeField()),
                ('dataDevolucao', models.DateTimeField()),
                ('ledor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervum.leitor')),
            ],
        ),
    ]
