# Generated by Django 4.2.2 on 2023-06-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
